"""
EQT Hybrid Strategy — Standalone Streamlit App
Loads the pre-computed backtest JSON from data/eqt_backtest.json.
Run locally first:  python run_backtest.py
"""
import pathlib
import streamlit as st
import eqt_hybrid_tab

st.set_page_config(
    page_title="EQT Hybrid Strategy",
    page_icon="🛢️",
    layout="wide",
)

st.markdown("""
<style>
:root{--bg:#0f1117;--card:#1a1d27;--ink:#e8eaf0;--mut:#94a3b8;--line:#2d3148;--accent:#7c3aed;}
html,body,[class*="css"]{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;}
.stApp{background:var(--bg);}
.block-container{max-width:1200px;padding-top:1.2rem;padding-bottom:3rem;}
h1,h2,h3{color:var(--ink);}
div[data-testid="stMetric"]{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:10px 14px;}
div[data-testid="stMetricLabel"] p{color:var(--mut);font-size:11px;}
div[data-testid="stMetricValue"]{font-size:20px;font-weight:680;color:var(--ink);}
section[data-testid="stSidebar"]{background:#12151f;border-right:1px solid var(--line);}
</style>
""", unsafe_allow_html=True)

# Locate the pre-computed JSON (generated by run_backtest.py)
_json = None
for _cand in [
    pathlib.Path(__file__).parent / "data" / "eqt_backtest.json",
    pathlib.Path(__file__).parent / "data" / "backtest_output.json",
]:
    if _cand.exists():
        _json = str(_cand)
        break

eqt_hybrid_tab.render_eqt_hybrid(json_path=_json)
